#!/usr/bin/env sh

# CHECK THIS PATH IS CORRECT FIRST! :)
export DOTFILES=~/dotfiles

# Remove existing links
rm ~/.gitconfig
rm ~/.zshenv
rm ~/.zshrc

rm ~/.config/starship.toml
rm ~/.config/nvim/init.vim

# Create symlinks
ln -s $DOTFILES/.gitconfig ~/.gitconfig
ln -s $DOTFILES/zsh/.zshenv ~/.zshenv
ln -s $DOTFILES/zsh/.zshrc ~/.zshrc

mkdir -p ~/.config/nvim/plugged

ln -s $DOTFILES/config/starship.toml ~/.config/starship.toml
ln -s $DOTFILES/config/init.vim ~/.config/nvim/init.vim

echo "Successerino friendino!"
