#!/usr/bin/env sh

# CHECK THIS PATH IS CORRECT FIRST! :)
export DOTFILES=~/dotfiles


# Remove existing links

rm ~/.gitconfig
rm ~/.zprofile
rm ~/.zshenv
rm ~/.zshrc

rm ~/.config/starship.toml
rm ~/.config/nvim/init.vim


# Create symlinks

ln -s $DOTFILES/.gitconfig ~/.gitconfig
ln -s $DOTFILES/zsh/.zprofile ~/.zprofile
ln -s $DOTFILES/zsh/.zshenv ~/.zshenv
ln -s $DOTFILES/zsh/.zshrc ~/.zshrc

# This is the dir for my NeoVim plugins, which is referenced in 
# ./config/init.vim. Creating/checking it is there also ensures the
# presence of the ./config dir and the nvim dir within that (winning!)
mkdir -p ~/.config/nvim/plugged

ln -s $DOTFILES/config/starship.toml ~/.config/starship.toml
ln -s $DOTFILES/config/init.vim ~/.config/nvim/init.vim


echo "Successerino friendino!"
