[directory]
truncation_length = 8

[git_commit]
style="bold purple"

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '

[git_status]
format = '(\[ [$all_status]($style)$ahead_behind\] )'
conflicted = '= '
stashed = '[$](bold yellow) '
deleted = 'x '
renamed = '» '
modified = "* "
staged = '[+](bold green) '
untracked = "[?](bold yellow) "
ahead = "⇡ "
behind = "⇣ "
diverged = "⇕ "
